name: 'epidemic'

on:
  watch:
    types: started
  push:
  schedule:
    - cron: '35 17,18,19 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v1
        - name: 'Set up Python'
          uses: actions/setup-python@v1
          with:
            python-version: '3.7'
        - name: 'Install requirements'
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Install ChromeDriver
          run: |
            CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
              && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
              && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
              && cd /tmp \
              && unzip chromedriver_linux64.zip \
              && rm -rf chromedriver_linux64.zip \
              && sudo mv chromedriver /usr/local/bin/chromedriver \
              && sudo chmod +x /usr/local/bin/chromedriver \
              && chromedriver --version
        - name: 'Get Date'
          # run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shenzhen' date '+%Y-%m-%d %T %Z')"
          # run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shenzhen' date -u -d"+8 hour" +'%Y-%m-%d %H:%M:%S')"
          run: echo "REPORT_DATE=$(TZ=':Asia/Shenzhen' date -u -d"+8 hour" +'%Y-%m-%d %H:%M:%S')">> $GITHUB_ENV
        - name: 'AutoClick'
          env:
            ActonMartin_USER: ${{ secrets.ActonMartin_USER }}
            ActonMartin_PASSWORD: ${{ secrets.ActonMartin_PASSWORD }}
            VPN1_USER: ${{ secrets.VPN1_USER }}
            VPN1_PASSWORD: ${{ secrets.VPN1_PASSWORD }}
            VPN2_USER: ${{ secrets.VPN2_USER }}
            VPN2_PASSWORD: ${{ secrets.VPN2_PASSWORD }}
          run: python autoclick.py
        - name: 'Send mail'
          uses: dawidd6/action-send-mail@master
          with:
            server_address: smtp.88.com
            server_port: 465
            username: ${{ secrets.MAIL_USERNAME }}
            password: ${{ secrets.MAIL_PASSWORD }}
            subject: 三峡大学健康申报系统操作结果 
            body: file://email.txt
            to: 2652863980@qq.com
            from: GitHub Actions
            content_type: text/html
